# Generated by Django 3.0.5 on 2020-04-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
